<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2023 IBM                                                             -->
<!-- Licensed under the Apache License, Version 2.0 (the "License");                -->
<!-- you may not use this file except in compliance with the License.               -->
<!-- You may obtain a copy of the License at                                        -->
<!--                                                                                -->
<!--    http://www.apache.org/licenses/LICENSE-2.0                                  -->
<!--                                                                                -->
<!-- Unless required by applicable law or agreed to in writing, software            -->
<!-- distributed under the License is distributed on an "AS IS" BASIS,              -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.       -->
<!-- See the License for the specific language governing permissions and            -->
<!-- limitations under the License.IBM Confidential                                 -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ibm.odm</groupId>
    <artifactId>decisioncenter</artifactId>
    <version>8.12.0.1</version>
    <packaging>pom</packaging>

    <properties>
        <decisioncenter.lib>${odm.home}/teamserver/lib</decisioncenter.lib>
        <repositoryId>define your repository id</repositoryId>
        <repositoryUrl>define your repository url</repositoryUrl>
        <groupId>com.ibm.odm</groupId>
        <odm.version>${project.version}</odm.version>
    </properties>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.4</version>
                    <executions>
                        <execution>
                            <id>default-deploy</id>
                            <phase>deploy</phase>
                            <configuration>
                                <skip>true</skip>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <repositoryId>${repositoryId}</repositoryId>
                    <url>${repositoryUrl}</url>
                    <groupId>${groupId}</groupId>
                    <version>${odm.version}</version>
                    <packaging>jar</packaging>
                </configuration>
                <executions>
                    <execution>
                        <id>deploy-bdsl-dtx-core</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/bdsl-dtx-core.jar</file>
                            <artifactId>bdsl-dtx-core</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-common-rs4jutils</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-common-rs4jutils.jar</file>
                            <artifactId>jrules-common-rs4jutils</artifactId>
                        </configuration>
                    </execution>
                    <execution>
                        <id>deploy-jrules-dataaccess-rs4j</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-dataaccess-rs4j.jar</file>
                            <artifactId>jrules-dataaccess-rs4j</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-decisionservice-model</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-decisionservice-model.jar</file>
                            <artifactId>jrules-decisionservice-model</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-decisionservice</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-decisionservice.jar</file>
                            <artifactId>jrules-decisionservice</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-engine</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-engine.jar</file>
                            <artifactId>jrules-engine</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-language</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-language.jar</file>
                            <artifactId>jrules-language</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-model-dataaccess</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-model-dataaccess.jar</file>
                            <artifactId>jrules-model-dataaccess</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-model-xml</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-model-xml.jar</file>
                            <artifactId>jrules-model-xml</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-res-tools</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-res-tools.jar</file>
                            <artifactId>jrules-res-tools</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-ruleartifacts</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-ruleartifacts.jar</file>
                            <artifactId>jrules-ruleartifacts</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-services</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-services.jar</file>
                            <artifactId>jrules-services</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-synchronization</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-synchronization.jar</file>
                            <artifactId>jrules-synchronization</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-teamserver</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-teamserver.jar</file>
                            <artifactId>jrules-teamserver</artifactId>
                        </configuration>
                    </execution>

                    <execution>
                        <id>deploy-jrules-validation</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/jrules-validation.jar</file>
                            <artifactId>jrules-validation</artifactId>
                        </configuration>
                    </execution>
                    <execution>
                        <id>deploy-decisioncenter-dependencies</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/decisioncenter-dependencies.xml</file>
                            <artifactId>decisioncenter-dependencies</artifactId>
                            <packaging>pom</packaging>
                        </configuration>
                    </execution>

                    <!-- Deploy some required third party jars missing in maven central -->

                    <execution>
                        <id>deploy-json4j</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/json4j-1.0.0.2.jar</file>
                            <groupId>com.ibm.json</groupId>
                            <artifactId>json4j</artifactId>
                            <version>1.0.0.2</version>
                        </configuration>
                    </execution>
                    <execution>
                        <id>deploy-serializer</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/serializer-2.7.3.IBM.jar</file>
                            <groupId>com.ibm.serializer</groupId>
                            <artifactId>serializer</artifactId>
                            <version>2.7.3.IBM</version>
                        </configuration>
                    </execution>
                    <execution>
                        <id>deploy-xalan</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <file>${decisioncenter.lib}/xalan-2.7.3.IBM.jar</file>
                            <groupId>com.ibm.xalan</groupId>
                            <artifactId>xalan</artifactId>
                            <version>2.7.3.IBM</version>
                            <pomFile>${project.basedir}/internal/xalan.pom</pomFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
